### ISSUE TITLE
extension force-disabled when trying to allow in incognito (windows only)

### ISSUE THREAD

**Issue by Simon0Harms** [ttyridal/masterpassword-chrome#1]
When i activate the incognito mode in chrome://extensions/, the whole extension is deaktivated...

**Comment by ttyridal** [comment]
Hi, What OS, chrome version and do you have other extensions installed?

**Comment by Simon0Harms** [comment]
40.0.2214.111

Yesterday i had no extensions installed and this error occur.

Today another installed addon is hangouts

**Comment by ttyridal** [comment]
Windows, Linux, Mac? 64bit?

Just to be sure, you did it like this?
https://github.com/ttyridal/masterpassword-chrome/wiki#incognito-mode

**Comment by Simon0Harms** [comment]
jep, exactly like this.
Win 7 Enterprise SP1 (64 Bit) with 40.0.2214.111 m
(but i can it only test today if the error is fixed)

The Problem do NOT OCCUR on Ubuntu 14.04 (64 Bit) with 40.0.2214.95 (64 Bit)
The Problem do NOT OCCUR on Ubuntu 14.04 (64 Bit) with 40.0.2214.111 (64 Bit)

**Comment by ttyridal** [comment]
Ouch.. That was a rather unpleasing experience.  issue confirmed.

At first glance it seems like like this is a new security feature in chrome.  It will be interesting to see as I get to test new linux (and osx) releases. Chrome is rather hostile to extensions not comming from the web-store (working on that). 

a workaround is to extract the crx file (it's just a .zip, use 7-zip or similar), enable developer mode in chrome and "load unpacked extension".  But it's a rather unsatisfying solution.

**Comment by Simon0Harms** [comment]
no important for me, i mostly use firefox and extremly rare use windows. ;)

I only wanted to inform you, this addon is really great =)

**Comment by ttyridal** [comment]
I've finally come around to place the addon on the [chrome store](https://chrome.google.com/webstore/detail/masterpassword-for-chrome/hifbblnjfcimjnlhibannjoclibgedmd?hl=en-US&gl=US).  Please reopen if this is still an issue.
