### ISSUE TITLE
Problems upon importing .mpsites files

### ISSUE THREAD

**Issue by jan-car** [ttyridal/masterpassword-chrome#11]
I'm using the Master Password App on my Android phone and found this chrome extension to be very useful!
The only problem is that I get a "Key ID mismatch!" error when I try to import (via drag&drop) my stored sites, which I exported from the Android app.
After examining the `.mpsites` file, I found that the "Password type" of my Android sites are usually
`16:3:1`
but when I export sites from your Chrome extension, I get
`16:1:1`
instead. After importing the `.mpsites` file, the `ver` column also shows `1` everywhere (I assume, it should be `3`).
I assume the first number determines the password type (maximum: `16`, long: `17`, etc.), the last number determines the count ("times used" in `.mpsites`?) and the second number determines the algorithm version?
Do you have an idea, why the import does not recognize the correct version? Is there a setting I did overlook?

**Comment by ttyridal** [comment]
Hi,

the key id mismatch should have been fixed in version 2.1.4, it relates to the keyId field in .mpsites. Are you using an older version?

With regards to the second field in sites, You're correct. It's the algorithm version. The plugin only really handles version 3 and will warn you if you violate this on import (and export). 

The difference between versions is handling of non-7-bit-ascii characters in site name (ver 2) and user name (ver 3). If your username and site name only contains 7-bit ascii, all algorithm versions give the same result. The plugin will write the lowest required version to produce the correct password.

**Comment by jan-car** [comment]
Thanks for the fast response!
I'm indeed using version 2.1.4. so that should not be the issue...
I tested the extension without importing things first and the `.mpsites` file that can be exported has the following lines in the header:
```
# Format: 1
# Date: 2017-10-10T17:14:56.19Z
...
# Avatar: 0
# Key ID: **redacted**
# Version: 2.2
# Algorithm: 3
# Default Type: 17
# Passwords: PROTECTED
```
For the site, it set the password type to `17:1:1`, so apparently the default is still fixed to version 1 of the algorithm(?). Is there a setting I missed?

I also tried importing the `.mpsites` file from the Android App (with `16:3:1` for every password type) again and they are converted to `16:1:1` for every site.

My username only consists of alphabetical letters and a space and the sites are named as suggested in the GitHub Readme.

**Comment by ttyridal** [comment]
> I also tried importing the .mpsites file from the Android App (with 16:3:1 for every password type) again and they are converted to 16:1:1 for every site.

Yes, that would be the correct behaviour. Now if you try `torbjørn@google.com` (notice non-ascii `ø`) as the site name, you'll notice that the version bumps to **2**. Similar, if the user name was `Torbjørn Tyridal`, the version would be **3**

without those `ø`'s (or à, é, ß, 屋 etc) the algorithm versions are compatible and the plugin does not track this property. (and as said, will put the "minimum required version" as the alg.version in .mpsites)

Anyhow, this should be unrelated to the  "Key ID mismatch!" warning.

Do you get the correct passwords generated for sites from both apps? Are you certain the user name and password for the two are *identical* (casing, spaces etc)? If you export an mpsites from both, does the ` #Key ID` match?

**Comment by jan-car** [comment]
Ah, I didn't understand that the minimum required version is listed (as the Android App apparently uses the latest version 3 as a default, even if it would not be necessary).
Your test cases worked exactly as expected, so there is no error there.
Strangely enough, I tried the whole procedure on my old Windows 7 machine (also with the Chrome extension) and everything worked fine, without the "Key ID Mismatch!" warning. I also get the correct passwords.

EDIT: Ok, after reinstalling Chrome and the extension on my Windows 10 machine (where the error occured originally, including wrongly generated passwords), the "Key ID Mismatch!" does no longer occur. And I also get correct passwords now (and the Key ID is the same now too, which was not the case before). Seems like everything works correctly now. Very strange, but I won't complain :-)... Thanks for your patient explanations, I hope this did not waste your time.
