### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-chrome#2]
It would be great if the chrome version mirrored the firefox version's functionality of importing and exporting sites, read https://github.com/ttyridal/masterpassword-firefox/issues/5 for more information.

**Comment by ttyridal** [comment]
I totally agree.  It seems the firefox version is vastly more popular though, so this copy has received a lot less attention after fulfilling my own needs.  A feature sync is on the list.

**Comment by ttyridal** [comment]
That's hopefully addressed with today's release.
