### ISSUE TITLE
Extension being auto disabled on Chrome

### ISSUE THREAD

**Issue by bakkerme** [ttyridal/masterpassword-chrome#3]
So Chrome appears to be automatically disabling extensions not from the Chrome Store, with no possibility to turn it back on unless you reinstall it. Do you have any intention to upload the extension to the Chrome Store?

**Comment by ttyridal** [comment]
Now on [chrome store](https://chrome.google.com/webstore/detail/masterpassword-for-chrome/hifbblnjfcimjnlhibannjoclibgedmd?hl=en-US&gl=US)
