### ISSUE TITLE
key installation fails

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-chrome#5]
OpenSuse leap 42.2

the cli command
@linux-9vc6:~/rpmd/firefox> sudo python pwvault_gateway_dbus.py install --global kwallet chrome
root's password:
Installed /usr/local/bin/pwvault_gateway_kde
Created etc/opt/chrome/native-messaging-hosts/no.ttyridal.pwvault_gateway.json
@linux-9vc6:~/rpmd/firefox> 

- python script creates etc/opt/chrome/native-messaging-hosts/no.ttyridal.pwvault_gateway.json
in the folder containing the python script instead of root partition
- the path /etc/opt/chrome/ is not good. there is nothing in /etc/opt/
the good one is /opt/google/chrome/

i tried to copy native-messaging-hosts/no.ttyridal.pwvault_gateway.json in /etc/opt/chrome/  but no success
i tried to copy no.ttyridal.pwvault_gateway.json in /etc/opt/chrome/ but no success

no success = masterpaswword is not recorded and "system password vault fails. help?"

**Comment by ttyridal** [comment]
The path should be right, ref https://developer.chrome.com/extensions/nativeMessaging

What does the browser log say? (try executing chrome from a terminal window) Unfortunately the diagnostic feedback from the browser is very poor when it comes to native messaging.

Are you using chrome or chromium? The paths are different. (might just as well do `sudo python pwvault_gateway_dbus.py install --global kwallet all` to be sure)

Have you tried without the `--global` flag (and no sudo)

**Comment by promeneur** [comment]
don't miss the first problem:
python script creates etc/opt/chrome/native-messaging-hosts/no.ttyridal.pwvault_gateway.json
in the folder containing the python script instead of root partition

**Comment by promeneur** [comment]
i copied chrome/native-messaging-hosts/no.ttyridal.pwvault_gateway.json in /etc/opt/
then
no more problem

**Comment by ttyridal** [comment]
Ah. now it should be better. Thanks

**Comment by promeneur** [comment]
Pb still there.

the script (with --global and chrome) is buggy.

the scrip erroneously puts no.ttyridal.pwvault_gateway.json in ~/../folder/etc/opt/chrome/native-messaging-hosts/ where folder is the folder containing the python script instead of putting it to /etc/opt/chrome/native-messaging-hosts/

**Comment by ttyridal** [comment]
Hm... Where did you download the python script?  I found a bad link on the wiki page - fixed now.

**Comment by promeneur** [comment]
i used link in the wiki
