### ISSUE TITLE
merge mpsites from FF mpw to chrome mpw, missing cases

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-chrome#6]
With FF mpw I export mpsites
then
I drag and drop the export file to “stored sites” in chrome mpw
then
there is 2 differences:
1.
In FFmpw
amazon.fr amazon.com   x@y.fr
amazon.fr amazon.de     x@y.fr
amazon.fr amazon.co.uk x@y.fr
amazon.fr amazon.fr       x@y.fr

in Chrome mpw
amazon.fr amazon.fr       x@y.fr

2.
In FF mpw
moncompte.sncf.com sncf.com x@y.fr
ter.sncf.com                sncf.com x@y.fr
in Chrome mpw
moncompte.sncf.com moncompte.sncf.com x@y.fr
ter.sncf.com                ter.sncf.com               x@y.fr

**Comment by ttyridal** [comment]
Yes, this is https://github.com/ttyridal/masterpassword-firefox/issues/44

The current .mpsites format can not store the url match so we have to guess

**Comment by ttyridal** [comment]
fixed in the latest release if using mpjson format for export/import
