### ISSUE TITLE
Key ID Mismatch

### ISSUE THREAD

**Issue by Volkor3-16** [ttyridal/masterpassword-chrome#7]
Same issue as ttyridal/masterpassword-firefox#48

I believe this breaks all passwords generated from the chrome app, generating passwords that are completely different to the official versions.

**Comment by ttyridal** [comment]
Hi, do you have an example of this incompatibility?  While the case mismatch in the textual representation will generate a warning all passwords are derived from your master key and should not be affected.

**Comment by Volkor3-16** [comment]
For this I'm using the Fullname of "TestUser1" with the password of "github"

https://i.imgur.com/0WXf0UA.png

I've used the same .mpsites config from the java app.
And then again without the .mpsites, but copying the settings manually.

http://i.imgur.com/R4Xvz4L.png

I have switched the V3 to V0-3, it hasn't changed to the correct password.

**Comment by ttyridal** [comment]
That's interesting. C version from masterpasswordapp.com and https://js.masterpasswordapp.com/ both gives the same result as the firefox/chrome addon...

**Comment by ttyridal** [comment]
Just noticed from your images: You have a case mismatch in the username.. In the desktop version you are using "Test**u**ser1" (lowercase 'u') while in browser version you're using "Test**U**ser1" (uppercase 'u').

**Comment by Volkor3-16** [comment]
Thanks, that lead me to figure out that I was using V0 on the Java app and the web version is on V3. 

Damn, Thanks again, I'll be changing my all passwords again :\
