### ISSUE TITLE
Several problems with saving and restoring password info

### ISSUE THREAD

**Issue by tlewis3348** [ttyridal/masterpassword-chrome#8]
I've been having the following problems:

1. The password settings I select when I'm on a site don't get saved. Maybe some sort of notification should be sent when a password has been saved, and maybe a button should be added to the UI to allow the user to tell the extension when he wants the information to be saved. I have well over 100 passwords that I need to keep track of, but currently, the app/extension only keeps track of the settings for about half of them.
2. The settings page is completely unresponsive to my clicks when I click the "Export" button.
3. Nothing happens when I try to import a .mpsites file with all 100+ password settings entered.

At this point, I'm storing my passwords in Google Chrome's password manager and just using Master Password to generate the passwords. I'd like to use Master Password exclusively, but until it can be depended upon to be able to manage all of my passwords, I can't do that.

**Comment by ttyridal** [comment]
You are hitting the quota for [storage.sync](https://developer.chrome.com/extensions/storage) and apparently there is a bug not checking for the return value. 

Note that sites with no customization (ie no change to site name, counter or password length and no user name) are not saved by design. @tlewis3348, Do you think all sites where you clicked MP should get saved? A button could make it user selectable, but it would also clutter the interface and generate frustration whenever one forgets to push it (I think click-to-save is very "old-school" these days)

When you click export, does it not save a `chrome.mpsites` to your download folder?  some ui feedback might be appropriate though.

**Comment by tlewis3348** [comment]
> You are hitting the quota for storage.sync and apparently there is a bug not checking for the return value.

Is there anything I can do on my end to make the quota larger or in some way make it less likely that I hit it?

> Note that sites with no customization (ie no change to site name, counter or password length and no user name) are not saved by design. @tlewis3348, Do you think all sites where you clicked MP should get saved? A button could make it user selectable, but it would also clutter the interface and generate frustration whenever one forgets to push it (I think click-to-save is very "old-school" these days)

I also want to use the exported file to import my password settings into the Master Password [Android app](https://play.google.com/store/apps/details?id=de.devland.masterpassword). In order for that to work effectively, I believe all the sites (even the ones with the default settings) need to be included in the exported information and therefore in the saved list of sites. Even so, even when I enter my username (which I've been doing for all sites) and change the default settings, these settings still don't get saved. This might be due to hitting the storage.sync quota.

> When you click export, does it not save a chrome.mpsites to your download folder? some ui feedback might be appropriate though.

No file is saved. It feels like it should bring up the typical window asking me where I want to save the file and what I want to name it. Maybe you could have a separate option to set the path and filename so this same functionality is available while not requiring it to be done each time the user exports their site settings. Obviously, having a notification letting the user know that the file had been saved would be nice too.

**Comment by ttyridal** [comment]
> Is there anything I can do on my end to make the quota larger or in some way make it less likely that > I hit it?

Unfortunately, I don't think so.

**Comment by ttyridal** [comment]
@tlewis3348 Do you see anything in the log when export is failing  (bring up the log with Ctrl-Shift-J)

**Comment by tlewis3348** [comment]
Here's the contents of the log:

>options.js:108 Failed loading state from background on popup
>chrome.extension.getBackgroundPage.store_get.then.catch @ options.js:108
>
>mpw-utils.js:170 Uncaught unknown password type
>(anonymous) @ mpw-utils.js:170
>(anonymous) @ mpw-utils.js:154
>make_mpsites @ mpw-utils.js:153
>(anonymous) @ options.js:285

The first occurs when the page opens. The second occurs when the "Export" button is clicked.

**Comment by ttyridal** [comment]
fixed and released
